version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: db.dockerfile
    container_name: db
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  web_front:
    build:
      context: .
      dockerfile: front.dockerfile
    container_name: front
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./front:/front
    working_dir: /front
    command: ["python", "app.py"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/CGDP_DB
