services:
  db:
    build: 
      context: https://github.com/devAlexA00/CGDP.git
      dockerfile: db/Dockerfile
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root user's password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  app:
    build:
      context: https://github.com/devAlexA00/CGDP.git
      dockerfile: app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "5000:5000"
