version: '3'
services:
  sqlite-db:
    build:
      context: .
      dockerfile: Dockerfile_sql
    container_name: sqlite-db

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    container_name: flask-app
    depends_on:
      - sqlite-db
    ports:
      - "5000:5000"
