# Use the official Python slim image as a base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install required packages
RUN apt-get update && \
    apt-get install -y sqlite3 wget && \
    apt-get clean

# Download the create_db.sh script from GitHub raw content URL
RUN wget https://raw.githubusercontent.com/BlinerZ/Projet_Info0803/main/create_db.sh -O create_db.sh

# Download the contacts_dump.sql file from GitHub raw content URL
RUN wget https://raw.githubusercontent.com/BlinerZ/Projet_Info0803/main/contacts_dump.sql -O contacts_dump.sql

# Make the shell script executable
RUN chmod +x create_db.sh

# Run the shell script when the container starts
CMD ["./create_db.sh"]
